# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

backsolveBatchBackend <- function(C, A, B, Cstartend, Astartend, Bstartend, numbatchB, diagIsOne, Nglobal, Nlocal, NlocalCache = 1000L, verbose = 0L) {
    .Call('_gpuBatchMatrix_backsolveBatchBackend', PACKAGE = 'gpuBatchMatrix', C, A, B, Cstartend, Astartend, Bstartend, numbatchB, diagIsOne, Nglobal, Nlocal, NlocalCache, verbose)
}

cholBatchBackend <- function(A, D, Astartend, Dstartend, numbatchD, Nglobal, Nlocal, NlocalCache) {
    invisible(.Call('_gpuBatchMatrix_cholBatchBackend', PACKAGE = 'gpuBatchMatrix', A, D, Astartend, Dstartend, numbatchD, Nglobal, Nlocal, NlocalCache))
}

#' Multiply crossproduct matrices
#' 
#' Computes C = t(A) D A
crossprodBatchBackend <- function(C, A, D, invertD, Cstartend, Astartend, Dstartend, Nglobal, Nlocal, NlocalCache) {
    .Call('_gpuBatchMatrix_crossprodBatchBackend', PACKAGE = 'gpuBatchMatrix', C, A, D, invertD, Cstartend, Astartend, Dstartend, Nglobal, Nlocal, NlocalCache)
}

#' 
#' Multiplies a rectangular matrix by a rectangular matrix in batches
#'
#' @param C output matrices, stacked row-wise
#' @param A rectangular matrices
#' @param B rectangular matrices 
#' @param Nglobal vector of number of global work items//' @param Nlocal vector of number of local work items//' @param NlocalCache elements in local cache
#' @export
gemmBatch2backend <- function(A, B, C, transposeABC, submatrixA, submatrixB, submatrixC, batches, workgroupSize, NlocalCache, verbose) {
    .Call('_gpuBatchMatrix_gemmBatch2backend', PACKAGE = 'gpuBatchMatrix', A, B, C, transposeABC, submatrixA, submatrixB, submatrixC, batches, workgroupSize, NlocalCache, verbose)
}

likfitGpu_BackendP <- function(yx, coords, params, boxcox, betas, ssqY, aTDinvb_beta, XVYXVX, ssqBetahat, ssqBeta, detVar, detReml, jacobian, NparamPerIter, workgroupSize, localSize, NlocalCache, verbose, ssqYX, ssqYXcopy, LinvYX, QinvSsqYx, cholXVXdiag, varMat, cholDiagMat, b_beta) {
    invisible(.Call('_gpuBatchMatrix_likfitGpu_BackendP', PACKAGE = 'gpuBatchMatrix', yx, coords, params, boxcox, betas, ssqY, aTDinvb_beta, XVYXVX, ssqBetahat, ssqBeta, detVar, detReml, jacobian, NparamPerIter, workgroupSize, localSize, NlocalCache, verbose, ssqYX, ssqYXcopy, LinvYX, QinvSsqYx, cholXVXdiag, varMat, cholDiagMat, b_beta))
}

mat_vec_eledivideBackend <- function(matrixR, rowvectorR, resultR, numWorkItems) {
    invisible(.Call('_gpuBatchMatrix_mat_vec_eledivideBackend', PACKAGE = 'gpuBatchMatrix', matrixR, rowvectorR, resultR, numWorkItems))
}

matrix_vector_sumBackend <- function(matrixR, rowvectorR, colvectorR, constantR, sumR, numWorkItems) {
    invisible(.Call('_gpuBatchMatrix_matrix_vector_sumBackend', PACKAGE = 'gpuBatchMatrix', matrixR, rowvectorR, colvectorR, constantR, sumR, numWorkItems))
}

fillParamsExtra <- function(param) {
    invisible(.Call('_gpuBatchMatrix_fillParamsExtra', PACKAGE = 'gpuBatchMatrix', param))
}

maternBatchBackend <- function(var, coords, param, Nglobal, Nlocal, startrow, numberofrows, verbose = 0L) {
    invisible(.Call('_gpuBatchMatrix_maternBatchBackend', PACKAGE = 'gpuBatchMatrix', var, coords, param, Nglobal, Nlocal, startrow, numberofrows, verbose))
}

multiplyLowerDiagonalBatchBackend <- function(output, L, D, B, diagIsOne, transformD, Nglobal, Nlocal, NlocalCache) {
    .Call('_gpuBatchMatrix_multiplyLowerDiagonalBatchBackend', PACKAGE = 'gpuBatchMatrix', output, L, D, B, diagIsOne, transformD, Nglobal, Nlocal, NlocalCache)
}

multiplyDiagonalBatchBackend <- function(C, A, B, inverse, Nglobal, Nlocal) {
    .Call('_gpuBatchMatrix_multiplyDiagonalBatchBackend', PACKAGE = 'gpuBatchMatrix', C, A, B, inverse, Nglobal, Nlocal)
}

#' Multiply lower triangular matrices
#' 
#' Multiplies a lower triangular matrix by a rectangular matrix
#'
#' @param C output matrices, stacked row-wise
#' @param A lower triangular matrices
#' @param B rectangular matrix or matrices
#' @param Nglobal vector of number of global work items: Drow, Dcol, Dmatrix
#' @param Nlocal vector of number of local work items anything, anything, 1
#' @param NlocalCache elements in local cache
#' @export
multiplyLowerBatchBackend <- function(C, A, B, diagIsOne, Nglobal, Nlocal, NlocalCache) {
    .Call('_gpuBatchMatrix_multiplyLowerBatchBackend', PACKAGE = 'gpuBatchMatrix', C, A, B, diagIsOne, Nglobal, Nlocal, NlocalCache)
}

